/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* press the button toggle the leds */

#include <stdint.h>
#include <stdio.h>

#include "../MCAL_Layer/mcal_stm32f407xx.h"

#define HIGH         1
#define Btn_pressed  HIGH

uint32_t g_button_pressed_count = 0;

int main(void)
{
	GPIO_PinConfig_t LedConfig;
	GPIO_PinConfig_t ButtonConfig;

	LedConfig.GPIO_PortIndex= PortD;
	LedConfig.GPIO_PinNumber= Pin_No_12;
	LedConfig.GPIO_PinMode= GPIO_MODE_OUT;
	LedConfig.GPIO_PinSpeed= GPIO_SPEED_FAST;
	LedConfig.GPIO_PinPuPdControl= GPIO_NO_PUPD;
	LedConfig.GPIO_PinPinOPType= GPIO_OP_TYPE_PP;

	GPIO_InitPin(LedConfig);
	LedConfig.GPIO_PinNumber= Pin_No_13;
	GPIO_InitPin(LedConfig);
	LedConfig.GPIO_PinNumber= Pin_No_14;
	GPIO_InitPin(LedConfig);
	LedConfig.GPIO_PinNumber= Pin_No_15;
	GPIO_InitPin(LedConfig);

	ButtonConfig.GPIO_PortIndex= PortA;
	ButtonConfig.GPIO_PinNumber= Pin_No_0;
	ButtonConfig.GPIO_PinMode= GPIO_MODE_IT_RT;
	ButtonConfig.GPIO_PinSpeed= GPIO_SPEED_FAST;
	ButtonConfig.GPIO_PinPuPdControl= GPIO_NO_PUPD;
	ButtonConfig.GPIO_PinPinOPType= GPIO_OP_TYPE_PP;
	GPIO_InitPin(ButtonConfig);
	uint8_t i;

	while(1){

		printf("waiting to press the Button\n");

		if((GPIO_ReadInputPin(PortA, Pin_No_0))==Btn_pressed) {

			// some delay until button debouncing gets over
			Delay_Btn();

			g_button_pressed_count++;

			printf("Button is pressed : %lu\n",g_button_pressed_count);

			for(i=12 ;i<=15 ;i++){
				Delay();
				GPIO_ToggleOutputPin(PortD, i);
				Delay();
			}

		}

	}

}

