/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "../MCAL/GPIO/GPIO.h"

int main(void)
{
	// if array of pointers are static , you need to include GPIO.c
	// and if you remove static, include GPIO.h only, and extern them from GPIO.h
	// RCC_Port_AHB1ClockEnable_Registers[PortA]->Register=0x1;
	//RCC_Port_ClockConfig_Register[0]->bits.MCO1= 0x01;
	//RCC_Port_ClockConfig_Register[0]->bits.MCO1= 0x00;

	// access the pointer register
	volatile RCC_CR_Register *RccControlRegister = (volatile RCC_CR_Register*) RCC_ClockControl;
	RccControlRegister->bits.HSION= 1;

	//volatile RCC_AHB1ENR_Register *portDClockEnableRegister = RCC_Port_AHB1ClockEnable_Registers[PortD];
	//portDClockEnableRegister->bits.GPIODEN= 0x1;
	GPIO_PeripheralClockControl(PortD, ENABLE);
	GPIORegisters gpio_regs= gpio_registers;

	gpio_regs.GPIO_PinConfig.GPIO_PortIndex= PortD;
	gpio_regs.GPIO_PinConfig.GPIO_PinNumber= Pin_No_12;
	gpio_regs.GPIO_PinConfig.GPIO_PinMode= GPIO_MODE_OUT;
	gpio_regs.GPIO_PinConfig.GPIO_PinSpeed= GPIO_SPEED_FAST;
	gpio_regs.GPIO_PinConfig.GPIO_PinPuPdControl= GPIO_NO_PUPD;
	gpio_regs.GPIO_PinConfig.GPIO_PinPinOPType= GPIO_OP_TYPE_PP;

	GPIO_Init(&gpio_regs);
	gpio_regs.GPIO_PinConfig.GPIO_PinNumber= Pin_No_13;
	GPIO_Init(&gpio_regs);
	gpio_regs.GPIO_PinConfig.GPIO_PinNumber= Pin_No_14;
	GPIO_Init(&gpio_regs);
	gpio_regs.GPIO_PinConfig.GPIO_PinNumber= Pin_No_15;
	GPIO_Init(&gpio_regs);

	while(1){
		int i,j;
		for(i=0 ;i<2 ;i++){
			GPIO_ToggleOutputPin(PortD, 12);
			delay();
			GPIO_ToggleOutputPin(PortD, 13);
			delay();
			GPIO_ToggleOutputPin(PortD, 14);
			delay();
			GPIO_ToggleOutputPin(PortD, 15);
			delay();
		}

		for(i=0 ;i<4 ;i++){
			delay();
			gpio_regs.GPIO_ODRControl_Registers[PortD]->Register= 0x0;
			delay();
			for(j=12; j<=15; j++)
				GPIO_ToggleOutputPin(PortD, i);
		}

	}
}
