/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* press the button toggle the leds */

#include <stdint.h>
#include <stdio.h>

#include "../MCAL_Layer/mcal_stm32f407xx.h"

// global shared variable between code and ISR
uint8_t volatile g_button_pressed = 0;
uint32_t g_button_pressed_count = 0;

int main(void)
{
	GPIO_PinConfig_t LedConfig;
	GPIO_PinConfig_t ButtonConfig;

	LedConfig.GPIO_PortIndex= PortD;
	LedConfig.GPIO_PinNumber= Pin_No_12;
	LedConfig.GPIO_PinMode= GPIO_MODE_OUT;
	LedConfig.GPIO_PinSpeed= GPIO_SPEED_FAST;
	LedConfig.GPIO_PinPuPdControl= GPIO_NO_PUPD;
	LedConfig.GPIO_PinPinOPType= GPIO_OP_TYPE_PP;

	GPIO_InitPin(LedConfig);
	LedConfig.GPIO_PinNumber= Pin_No_13;
	GPIO_InitPin(LedConfig);
	LedConfig.GPIO_PinNumber= Pin_No_14;
	GPIO_InitPin(LedConfig);
	LedConfig.GPIO_PinNumber= Pin_No_15;
	GPIO_InitPin(LedConfig);

	ButtonConfig.GPIO_PortIndex= PortA;
	ButtonConfig.GPIO_PinNumber= Pin_No_0;
	ButtonConfig.GPIO_PinMode= GPIO_MODE_IT_RT;
	ButtonConfig.GPIO_PinSpeed= GPIO_SPEED_FAST;
	ButtonConfig.GPIO_PinPuPdControl= GPIO_NO_PUPD;
	ButtonConfig.GPIO_PinPinOPType= GPIO_OP_TYPE_PP;
	GPIO_InitPin(ButtonConfig);

	Syscfg_ClockEnable (ENABLE);
	NVIC_IRQEnable (0, 6, ENABLE);

	uint8_t i;

	while(1){

		// Disable Interrupt
		EXTI_EnableDisableInterrupt(Pin_No_0, DISABLE);
		printf("waiting to press the Button\n");

		if(g_button_pressed){
			// some delay until button debouncing gets over
			Delay_Btn();
			g_button_pressed_count++;
			printf("Button is pressed : %lu\n",g_button_pressed_count);
			for(i=12 ;i<=15 ;i++){
				Delay();
				GPIO_ToggleOutputPin(PortD, i);
				Delay();
			}
			g_button_pressed = 0;
		}
		// Enable Interrupt
		EXTI_EnableDisableInterrupt(Pin_No_0, ENABLE);

	}

}

// This the Button Interrupt Handler
void EXTI0_IRQHandler(void){
	static int counter = 0;
	counter++;
	printf("The EXTI0 Interrupt has been executed : %d !!\n", counter);

	// Make this flag SET . if button pressed
	g_button_pressed = 1;

	// clearing of EXTI Interrupt pending bit
    GPIO_IRQHandling(Pin_No_0);

}
